// const massMark = 78;
// const massJohn = 92;
// const heightMark = 1.69;
// const heightJohn = 1.95;
// const BMIMark = massMark / heightMark ** 2;
// const BMIJohn = massJohn / (heightJohn * heightJohn);
// const heightMarkBMI = BMIMark > BMIJohn;
// console.log(BMIMark, BMIJohn, heightMarkBMI);
const massMark = 95;
const massJohn = 85;
const heightMark = 1.88;
const heightJohn = 1.76;
const BMIMark = massMark / heightMark ** 2;
const BMIJohn = massJohn / (heightJohn * heightJohn);
const heightMarkBMI = BMIMark > BMIJohn;
console.log(BMIMark, BMIJohn, heightMarkBMI);
